config/routes.rb
Rails.application.routes.draw do
  resources :blood_donates
  resources :notifications
  resources :user_queries
  resources :blood_requests


   devise_for :users,
    path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
    controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations' 
      }
  get "about", to: "static_pages#about"
  get "contact", to: "static_pages#contact"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  "static_pages#home"
end

app/models/blood_donate.rb
class BloodDonate < ApplicationRecord
  belongs_to :user
  belongs_to :blood_request
end

app/controllers/blood_donates_controller.rb
class BloodDonatesController < ApplicationController
  before_action :set_blood_donate, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :is_admin, except: [:index]
  # GET /blood_donates
  # GET /blood_donates.json
  def index
    @blood_donates = BloodDonate.all
  end

  # GET /blood_donates/1
  # GET /blood_donates/1.json
  def show
  end

  # GET /blood_donates/new
  def new
    @blood_donate = BloodDonate.new
  end

  # GET /blood_donates/1/edit
  def edit
  end

  # POST /blood_donates
  # POST /blood_donates.json
  def create
    @blood_donate = BloodDonate.new(blood_donate_params)

    respond_to do |format|
      if @blood_donate.save
        format.html { redirect_to @blood_donate, notice: 'Blood donate was successfully created.' }
        format.json { render :show, status: :created, location: @blood_donate }
      else
        format.html { render :new }
        format.json { render json: @blood_donate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blood_donates/1
  # PATCH/PUT /blood_donates/1.json
  def update
    respond_to do |format|
      if @blood_donate.update(blood_donate_params)
        format.html { redirect_to @blood_donate, notice: 'Blood donate was successfully updated.' }
        format.json { render :show, status: :ok, location: @blood_donate }
      else
        format.html { render :edit }
        format.json { render json: @blood_donate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blood_donates/1
  # DELETE /blood_donates/1.json
  def destroy
    @blood_donate.destroy
    respond_to do |format|
      format.html { redirect_to blood_donates_url, notice: 'Blood donate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
   

    # Use callbacks to share common setup or constraints between actions.
    def set_blood_donate
      @blood_donate = BloodDonate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blood_donate_params
      params.require(:blood_donate).permit(:user_id, :blood_request_id, :donate_date)
    end
end

app/helpers/blood_donates_helper.rb
module BloodDonatesHelper
end

app/views/blood_donates/_form.html.erb
<%= form_with(model: blood_donate, local: true) do |form| %>
  <% if blood_donate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blood_donate.errors.count, "error") %> prohibited this blood_donate from being saved:</h2>

      <ul>
      <% blood_donate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :blood_donate_user_id %>
  </div>

  <div class="field">
    <%= form.label :blood_request_id %>
    <%= form.text_field :blood_request_id, id: :blood_donate_blood_request_id %>
  </div>

  <div class="field">
    <%= form.label :donate_date %>
    <%= form.datetime_select :donate_date, id: :blood_donate_donate_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blood_donates/edit.html.erb
<h1>Editing Blood Donate</h1>

<%= render 'form', blood_donate: @blood_donate %>

<%= link_to 'Show', @blood_donate %> |
<%= link_to 'Back', blood_donates_path %>

app/views/blood_donates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blood Donates</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Blood request</th>
      <th>Donate date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blood_donates.each do |blood_donate| %>
      <tr>
        <td><%= blood_donate.user %></td>
        <td><%= blood_donate.blood_request %></td>
        <td><%= blood_donate.donate_date %></td>
        <td><%= link_to 'Show', blood_donate %></td>
        <td><%= link_to 'Edit', edit_blood_donate_path(blood_donate) %></td>
        <td><%= link_to 'Destroy', blood_donate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blood Donate', new_blood_donate_path %>

app/views/blood_donates/new.html.erb
<h1>New Blood Donate</h1>

<%= render 'form', blood_donate: @blood_donate %>

<%= link_to 'Back', blood_donates_path %>

app/views/blood_donates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @blood_donate.user %>
</p>

<p>
  <strong>Blood request:</strong>
  <%= @blood_donate.blood_request %>
</p>

<p>
  <strong>Donate date:</strong>
  <%= @blood_donate.donate_date %>
</p>

<%= link_to 'Edit', edit_blood_donate_path(@blood_donate) %> |
<%= link_to 'Back', blood_donates_path %>