config/routes.rb
Rails.application.routes.draw do
  resources :blood_donates
  resources :notifications
  resources :user_queries
  resources :blood_requests


   devise_for :users,
    path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
    controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations' 
      }
  get "about", to: "static_pages#about"
  get "contact", to: "static_pages#contact"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  "static_pages#home"
end

app/models/blood_request.rb
class BloodRequest < ApplicationRecord
	has_one :blood_donate
	enum blood_group: { "O-ve" => 0,"O+ve" => 1,"A+ve" => 2,"A-ve" => 3,"B+ve" => 4,"B-ve" => 5,"AB+ve" => 6,"AB-ve" => 7, } 
end

app/controllers/blood_requests_controller.rb
class BloodRequestsController < ApplicationController
  before_action :set_blood_request, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:new, :create]
  before_action :is_admin, except: [:new, :create, :index]
  # GET /blood_requests
  # GET /blood_requests.json
  def index
    @blood_requests = BloodRequest.all
  end

  # GET /blood_requests/1
  # GET /blood_requests/1.json
  def show
  end

  # GET /blood_requests/new
  def new
    @blood_request = BloodRequest.new
  end

  # GET /blood_requests/1/edit
  def edit
  end

  # POST /blood_requests
  # POST /blood_requests.json
  def create
    @blood_request = BloodRequest.new(blood_request_params)

    respond_to do |format|
      if @blood_request.save
        format.js {  flash[:notice] = "Thanks for your request. We will contact you soon."}
        format.html { redirect_to @blood_request, notice: 'Blood request was successfully created.' }
        format.json { render :show, status: :created, location: @blood_request }
      else
        format.js {  flash[:notice] = "Request failed, Please try again."}
        format.html { render :new }
        format.json { render json: @blood_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blood_requests/1
  # PATCH/PUT /blood_requests/1.json
  def update
    respond_to do |format|
      if @blood_request.update(blood_request_params)
        format.html { redirect_to @blood_request, notice: 'Blood request was successfully updated.' }
        format.json { render :show, status: :ok, location: @blood_request }
      else
        format.html { render :edit }
        format.json { render json: @blood_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blood_requests/1
  # DELETE /blood_requests/1.json
  def destroy
    @blood_request.destroy
    respond_to do |format|
      format.html { redirect_to blood_requests_url, notice: 'Blood request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blood_request
      @blood_request = BloodRequest.find(params[:id])
    end

      


    # Never trust parameters from the scary internet, only allow the white list through.
    def blood_request_params
      params.require(:blood_request).permit(:patient_name, :blood_group, :hospital_name, :city, :address, :contact_name, :email, :phone, :required_date)
    end
end

app/helpers/blood_requests_helper.rb
module BloodRequestsHelper
end

app/views/blood_requests/_form.html.erb
<%= form_with(model: blood_request, remote: true) do |form| %>
  <% if blood_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blood_request.errors.count, "error") %> prohibited this blood_request from being saved:</h2>

      <ul>
      <% blood_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="row">
    <div class="form-group col-md-6">
    <%= form.label :patient_name %>
    <%= form.text_field :patient_name, id: :blood_request_patient_name , class: "form-control", placeholder: "Patient Name*", :required => true%>
  </div>

  <div class="form-group col-md-6">
    <%= form.label :blood_group %>
    <%= form.select(:blood_group, [ "O+ve", "O-ve", "A+ve","A-ve","B+ve","B-ve","AB+ve","AB-ve"], { :prompt => 'Select Blood Group'}, { :class => 'form-control',:required => true }) %>
  </div>

  <div class="form-group col-md-6">
    <%= form.label :hospital_name %>
    <%= form.text_field :hospital_name, id: :blood_request_hospital_name,class: "form-control", placeholder: "Hospital Name" %>
  </div>

  <div class="form-group col-md-6">
     <%= form.label :city %><br />
     <%= form.select(:city, [ "kathmandu", "Bhaktapur", "Lalitpur"], { :prompt => 'Select City'}, { :class => 'form-control' }) %>
    </div>

  <div class="form-group col-md-6">
    <%= form.label :address %>
    <%= form.text_field :address, id: :blood_request_address,class: "form-control", placeholder: "Address*", :required => true %>
  </div>

  <div class="form-group col-md-6">
    <%= form.label :contact_name %>
    <%= form.text_field :contact_name, id: :blood_request_contact_name ,class: "form-control", placeholder: "Contact Name*", :required => true %>
  </div>

  <div class="form-group col-md-6">
    <%= form.label :email %>
    <%= form.email_field :email, id: :blood_request_email,class: "form-control", placeholder: "Email*", :required => true %>
  </div>

  <div class="form-group col-md-6">
    <%= form.label :phone %>
    <%= form.telephone_field :phone, id: :blood_request_phone,class: "form-control", placeholder: "Phone*", :required => true %>
  </div>

  <div class="form-group col-md-6">
    <%= form.label :required_date %>
    <%= form.date_field :required_date, id: :blood_request_required_date ,class: "form-control hasDatepicker", placeholder: " Required Date*", :required => true%>
  </div>

  <div class="form-group col-md-6">
    <br/>
    <%= form.submit "Send Request", class: "form-control btn btn-form" %>
  </div>
</div>
<% end %>

app/views/blood_requests/create.js.erb
$('form').trigger("reset");
$(".isa_success").append("<%=j flash[:notice] %>")
$(".isa_success").removeClass('hidden')
<% flash.clear%>
setTimeout(function(){
 	 	$('.isa_success').slideUp(300);
	}, 4000);

app/views/blood_requests/edit.html.erb
<h1>Editing Blood Request</h1>

<%= render 'form', blood_request: @blood_request %>

<%= link_to 'Show', @blood_request %> |
<%= link_to 'Back', blood_requests_path %>

app/views/blood_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blood Requests</h1>

<table>
  <thead>
    <tr>
      <th>Patient name</th>
      <th>Blood group</th>
      <th>Hospital name</th>
      <th>City</th>
      <th>Address</th>
      <th>Contact name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Required date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blood_requests.each do |blood_request| %>
      <tr>
        <td><%= blood_request.patient_name %></td>
        <td><%= blood_request.blood_group %></td>
        <td><%= blood_request.hospital_name %></td>
        <td><%= blood_request.city %></td>
        <td><%= blood_request.address %></td>
        <td><%= blood_request.contact_name %></td>
        <td><%= blood_request.email %></td>
        <td><%= blood_request.phone %></td>
        <td><%= blood_request.required_date %></td>
        <td><%= link_to 'Show', blood_request %></td>
        <td><%= link_to 'Edit', edit_blood_request_path(blood_request) %></td>
        <td><%= link_to 'Destroy', blood_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blood Request', new_blood_request_path %>

app/views/blood_requests/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8">
			<div class="isa_success hidden">
     				<i class="fa fa-check"></i>	
				</div>

			<h1>New Blood Request</h1>

			<%= render 'form', blood_request: @blood_request %>


		</div>
	</div>
</div>

app/views/blood_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient name:</strong>
  <%= @blood_request.patient_name %>
</p>

<p>
  <strong>Blood group:</strong>
  <%= @blood_request.blood_group %>
</p>

<p>
  <strong>Hospital name:</strong>
  <%= @blood_request.hospital_name %>
</p>

<p>
  <strong>City:</strong>
  <%= @blood_request.city %>
</p>

<p>
  <strong>Address:</strong>
  <%= @blood_request.address %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @blood_request.contact_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @blood_request.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @blood_request.phone %>
</p>

<p>
  <strong>Required date:</strong>
  <%= @blood_request.required_date %>
</p>

<%= link_to 'Edit', edit_blood_request_path(@blood_request) %> |
<%= link_to 'Back', blood_requests_path %>